### ISSUE TITLE
pip install errors out

### ISSUE THREAD

**Issue by DaforLynx** [HaxelWorks/qoa-python#1]
When trying `pip install qoa`, I get the following error:
```
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      Traceback (most recent call last):
        File "C:\Users\[user]\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\[user]\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 6, in <module>
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
                                       ~~~~~^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\dist.py", line 319, in __init__
          _Distribution.__init__(self, dist_attrs)
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__
          self.finalize_options()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\dist.py", line 677, in finalize_options
          ep(self)
          ~~^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\overlay\Lib\site-packages\setuptools\dist.py", line 697, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\normal\Lib\site-packages\cffi\setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\normal\Lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-ibdrq7zv\normal\Lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
          ~~~~^^^^^^^^^^^^^^^^^^
        File "qoa/ffi_builder.py", line 4, in <module>
          ffibuilder.cdef(open("qoa/cffi_def.h").read()) # load the C declarations from the file cdef.h
                          ~~~~^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'qoa/cffi_def.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

I have fully updated python and pip. The error appears to be part of cffi, but I figure you might want to know about it if you have an alternative solution.

**Comment by Axel-Roijers** [comment]
I'm able to reproduce. i'll look at it today
